/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct AuditRecordsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl AuditRecordsApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> AuditRecordsApiClient {
        AuditRecordsApiClient { configuration }
    }
}

pub trait AuditRecordsApi {
    fn get_audit_records(
        &self,
        offset: Option<i32>,
        limit: Option<i32>,
        filter: Option<&str>,
        from: Option<String>,
        to: Option<String>,
    ) -> Result<crate::models::AuditRecords, Error>;
}

impl AuditRecordsApi for AuditRecordsApiClient {
    fn get_audit_records(
        &self,
        offset: Option<i32>,
        limit: Option<i32>,
        filter: Option<&str>,
        from: Option<String>,
        to: Option<String>,
    ) -> Result<crate::models::AuditRecords, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/auditing/record", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = offset {
            req_builder = req_builder.query(&[("offset", &s.to_string())]);
        }
        if let Some(ref s) = limit {
            req_builder = req_builder.query(&[("limit", &s.to_string())]);
        }
        if let Some(ref s) = filter {
            req_builder = req_builder.query(&[("filter", &s.to_string())]);
        }
        if let Some(ref s) = from {
            req_builder = req_builder.query(&[("from", &s.to_string())]);
        }
        if let Some(ref s) = to {
            req_builder = req_builder.query(&[("to", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
