/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct DashboardsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl DashboardsApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> DashboardsApiClient {
        DashboardsApiClient { configuration }
    }
}

pub trait DashboardsApi {
    fn copy_dashboard_post(
        &self,
        id: &str,
        dashboard_request: crate::models::DashboardRequest,
    ) -> Result<crate::models::Dashboard, Error>;
    fn create_dashboard_post(
        &self,
        dashboard_request: crate::models::DashboardRequest,
    ) -> Result<crate::models::Dashboard, Error>;
    fn delete_dashboard(&self, id: &str) -> Result<(), Error>;
    fn delete_dashboard_item_property(
        &self,
        dashboard_id: &str,
        item_id: &str,
        property_key: &str,
    ) -> Result<(), Error>;
    fn get_all_dashboards(
        &self,
        filter: Option<&str>,
        start_at: Option<i32>,
        max_results: Option<i32>,
    ) -> Result<crate::models::PageOfDashboards, Error>;
    fn get_dashboard(&self, id: &str) -> Result<crate::models::Dashboard, Error>;
    fn get_dashboard_item_property(
        &self,
        dashboard_id: &str,
        item_id: &str,
        property_key: &str,
    ) -> Result<crate::models::EntityProperty, Error>;
    fn get_dashboard_item_property_keys(
        &self,
        dashboard_id: &str,
        item_id: &str,
    ) -> Result<crate::models::PropertyKeys, Error>;
    fn get_dashboards_paginated(
        &self,
        dashboard_name: Option<&str>,
        account_id: Option<&str>,
        owner: Option<&str>,
        groupname: Option<&str>,
        project_id: Option<i64>,
        order_by: Option<&str>,
        start_at: Option<i64>,
        max_results: Option<i32>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanDashboard, Error>;
    fn set_dashboard_item_property_put(
        &self,
        dashboard_id: &str,
        item_id: &str,
        property_key: &str,
        body: serde_json::Value,
    ) -> Result<serde_json::Value, Error>;
    fn update_dashboard_put(
        &self,
        id: &str,
        dashboard_request: crate::models::DashboardRequest,
    ) -> Result<crate::models::Dashboard, Error>;
}

impl DashboardsApi for DashboardsApiClient {
    fn copy_dashboard_post(
        &self,
        id: &str,
        dashboard_request: crate::models::DashboardRequest,
    ) -> Result<crate::models::Dashboard, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/dashboard/{id}/copy",
            configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&dashboard_request);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn create_dashboard_post(
        &self,
        dashboard_request: crate::models::DashboardRequest,
    ) -> Result<crate::models::Dashboard, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/dashboard", configuration.base_path);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&dashboard_request);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn delete_dashboard(&self, id: &str) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/dashboard/{id}",
            configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn delete_dashboard_item_property(
        &self,
        dashboard_id: &str,
        item_id: &str,
        property_key: &str,
    ) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}",
            configuration.base_path,
            dashboardId = crate::apis::urlencode(dashboard_id),
            itemId = crate::apis::urlencode(item_id),
            propertyKey = crate::apis::urlencode(property_key)
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn get_all_dashboards(
        &self,
        filter: Option<&str>,
        start_at: Option<i32>,
        max_results: Option<i32>,
    ) -> Result<crate::models::PageOfDashboards, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/dashboard", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = filter {
            req_builder = req_builder.query(&[("filter", &s.to_string())]);
        }
        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_dashboard(&self, id: &str) -> Result<crate::models::Dashboard, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/dashboard/{id}",
            configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_dashboard_item_property(
        &self,
        dashboard_id: &str,
        item_id: &str,
        property_key: &str,
    ) -> Result<crate::models::EntityProperty, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}",
            configuration.base_path,
            dashboardId = crate::apis::urlencode(dashboard_id),
            itemId = crate::apis::urlencode(item_id),
            propertyKey = crate::apis::urlencode(property_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_dashboard_item_property_keys(
        &self,
        dashboard_id: &str,
        item_id: &str,
    ) -> Result<crate::models::PropertyKeys, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties",
            configuration.base_path,
            dashboardId = crate::apis::urlencode(dashboard_id),
            itemId = crate::apis::urlencode(item_id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_dashboards_paginated(
        &self,
        dashboard_name: Option<&str>,
        account_id: Option<&str>,
        owner: Option<&str>,
        groupname: Option<&str>,
        project_id: Option<i64>,
        order_by: Option<&str>,
        start_at: Option<i64>,
        max_results: Option<i32>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanDashboard, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/dashboard/search", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = dashboard_name {
            req_builder = req_builder.query(&[("dashboardName", &s.to_string())]);
        }
        if let Some(ref s) = account_id {
            req_builder = req_builder.query(&[("accountId", &s.to_string())]);
        }
        if let Some(ref s) = owner {
            req_builder = req_builder.query(&[("owner", &s.to_string())]);
        }
        if let Some(ref s) = groupname {
            req_builder = req_builder.query(&[("groupname", &s.to_string())]);
        }
        if let Some(ref s) = project_id {
            req_builder = req_builder.query(&[("projectId", &s.to_string())]);
        }
        if let Some(ref s) = order_by {
            req_builder = req_builder.query(&[("orderBy", &s.to_string())]);
        }
        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn set_dashboard_item_property_put(
        &self,
        dashboard_id: &str,
        item_id: &str,
        property_key: &str,
        body: serde_json::Value,
    ) -> Result<serde_json::Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}",
            configuration.base_path,
            dashboardId = crate::apis::urlencode(dashboard_id),
            itemId = crate::apis::urlencode(item_id),
            propertyKey = crate::apis::urlencode(property_key)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn update_dashboard_put(
        &self,
        id: &str,
        dashboard_request: crate::models::DashboardRequest,
    ) -> Result<crate::models::Dashboard, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/dashboard/{id}",
            configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&dashboard_request);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
