/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct IssueNotificationSchemesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl IssueNotificationSchemesApiClient {
    pub fn new(
        configuration: Rc<configuration::Configuration>,
    ) -> IssueNotificationSchemesApiClient {
        IssueNotificationSchemesApiClient { configuration }
    }
}

pub trait IssueNotificationSchemesApi {
    fn get_notification_scheme(
        &self,
        id: i64,
        expand: Option<&str>,
    ) -> Result<crate::models::NotificationScheme, Error>;
    fn get_notification_schemes(
        &self,
        start_at: Option<i64>,
        max_results: Option<i32>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanNotificationScheme, Error>;
}

impl IssueNotificationSchemesApi for IssueNotificationSchemesApiClient {
    fn get_notification_scheme(
        &self,
        id: i64,
        expand: Option<&str>,
    ) -> Result<crate::models::NotificationScheme, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/notificationscheme/{id}",
            configuration.base_path,
            id = id
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_notification_schemes(
        &self,
        start_at: Option<i64>,
        max_results: Option<i32>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanNotificationScheme, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/notificationscheme", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
