/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct IssueCommentsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl IssueCommentsApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> IssueCommentsApiClient {
        IssueCommentsApiClient { configuration }
    }
}

pub trait IssueCommentsApi {
    fn add_comment_post(
        &self,
        issue_id_or_key: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        expand: Option<&str>,
    ) -> Result<crate::models::Comment, Error>;
    fn delete_comment(&self, issue_id_or_key: &str, id: &str) -> Result<(), Error>;
    fn get_comment(
        &self,
        issue_id_or_key: &str,
        id: &str,
        expand: Option<&str>,
    ) -> Result<crate::models::Comment, Error>;
    fn get_comments(
        &self,
        issue_id_or_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
        order_by: Option<&str>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageOfComments, Error>;
    fn get_comments_by_ids_post(
        &self,
        issue_comment_list_request_bean: crate::models::IssueCommentListRequestBean,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanComment, Error>;
    fn update_comment_put(
        &self,
        issue_id_or_key: &str,
        id: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        expand: Option<&str>,
    ) -> Result<crate::models::Comment, Error>;
}

impl IssueCommentsApi for IssueCommentsApiClient {
    fn add_comment_post(
        &self,
        issue_id_or_key: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        expand: Option<&str>,
    ) -> Result<crate::models::Comment, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/comment",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key)
        );
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn delete_comment(&self, issue_id_or_key: &str, id: &str) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/comment/{id}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn get_comment(
        &self,
        issue_id_or_key: &str,
        id: &str,
        expand: Option<&str>,
    ) -> Result<crate::models::Comment, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/comment/{id}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_comments(
        &self,
        issue_id_or_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
        order_by: Option<&str>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageOfComments, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/comment",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        if let Some(ref s) = order_by {
            req_builder = req_builder.query(&[("orderBy", &s.to_string())]);
        }
        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_comments_by_ids_post(
        &self,
        issue_comment_list_request_bean: crate::models::IssueCommentListRequestBean,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanComment, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/comment/list", configuration.base_path);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&issue_comment_list_request_bean);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn update_comment_put(
        &self,
        issue_id_or_key: &str,
        id: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        expand: Option<&str>,
    ) -> Result<crate::models::Comment, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/comment/{id}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
