/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct IssueWorklogsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl IssueWorklogsApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> IssueWorklogsApiClient {
        IssueWorklogsApiClient { configuration }
    }
}

pub trait IssueWorklogsApi {
    fn add_worklog_post(
        &self,
        issue_id_or_key: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        notify_users: Option<bool>,
        adjust_estimate: Option<&str>,
        new_estimate: Option<&str>,
        reduce_by: Option<&str>,
        expand: Option<&str>,
        override_editable_flag: Option<bool>,
    ) -> Result<crate::models::Worklog, Error>;
    fn delete_worklog(
        &self,
        issue_id_or_key: &str,
        id: &str,
        notify_users: Option<bool>,
        adjust_estimate: Option<&str>,
        new_estimate: Option<&str>,
        increase_by: Option<&str>,
        override_editable_flag: Option<bool>,
    ) -> Result<(), Error>;
    fn get_ids_of_worklogs_deleted_since(
        &self,
        since: Option<i64>,
    ) -> Result<crate::models::ChangedWorklogs, Error>;
    fn get_ids_of_worklogs_modified_since(
        &self,
        since: Option<i64>,
        expand: Option<&str>,
    ) -> Result<crate::models::ChangedWorklogs, Error>;
    fn get_issue_worklog(
        &self,
        issue_id_or_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
        started_after: Option<i64>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageOfWorklogs, Error>;
    fn get_worklog(
        &self,
        issue_id_or_key: &str,
        id: &str,
        expand: Option<&str>,
    ) -> Result<crate::models::Worklog, Error>;
    fn get_worklogs_for_ids_post(
        &self,
        worklog_ids_request_bean: crate::models::WorklogIdsRequestBean,
        expand: Option<&str>,
    ) -> Result<Vec<crate::models::Worklog>, Error>;
    fn update_worklog_put(
        &self,
        issue_id_or_key: &str,
        id: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        notify_users: Option<bool>,
        adjust_estimate: Option<&str>,
        new_estimate: Option<&str>,
        expand: Option<&str>,
        override_editable_flag: Option<bool>,
    ) -> Result<crate::models::Worklog, Error>;
}

impl IssueWorklogsApi for IssueWorklogsApiClient {
    fn add_worklog_post(
        &self,
        issue_id_or_key: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        notify_users: Option<bool>,
        adjust_estimate: Option<&str>,
        new_estimate: Option<&str>,
        reduce_by: Option<&str>,
        expand: Option<&str>,
        override_editable_flag: Option<bool>,
    ) -> Result<crate::models::Worklog, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/worklog",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key)
        );
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref s) = notify_users {
            req_builder = req_builder.query(&[("notifyUsers", &s.to_string())]);
        }
        if let Some(ref s) = adjust_estimate {
            req_builder = req_builder.query(&[("adjustEstimate", &s.to_string())]);
        }
        if let Some(ref s) = new_estimate {
            req_builder = req_builder.query(&[("newEstimate", &s.to_string())]);
        }
        if let Some(ref s) = reduce_by {
            req_builder = req_builder.query(&[("reduceBy", &s.to_string())]);
        }
        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref s) = override_editable_flag {
            req_builder = req_builder.query(&[("overrideEditableFlag", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn delete_worklog(
        &self,
        issue_id_or_key: &str,
        id: &str,
        notify_users: Option<bool>,
        adjust_estimate: Option<&str>,
        new_estimate: Option<&str>,
        increase_by: Option<&str>,
        override_editable_flag: Option<bool>,
    ) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/worklog/{id}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref s) = notify_users {
            req_builder = req_builder.query(&[("notifyUsers", &s.to_string())]);
        }
        if let Some(ref s) = adjust_estimate {
            req_builder = req_builder.query(&[("adjustEstimate", &s.to_string())]);
        }
        if let Some(ref s) = new_estimate {
            req_builder = req_builder.query(&[("newEstimate", &s.to_string())]);
        }
        if let Some(ref s) = increase_by {
            req_builder = req_builder.query(&[("increaseBy", &s.to_string())]);
        }
        if let Some(ref s) = override_editable_flag {
            req_builder = req_builder.query(&[("overrideEditableFlag", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn get_ids_of_worklogs_deleted_since(
        &self,
        since: Option<i64>,
    ) -> Result<crate::models::ChangedWorklogs, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/worklog/deleted", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = since {
            req_builder = req_builder.query(&[("since", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_ids_of_worklogs_modified_since(
        &self,
        since: Option<i64>,
        expand: Option<&str>,
    ) -> Result<crate::models::ChangedWorklogs, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/worklog/updated", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = since {
            req_builder = req_builder.query(&[("since", &s.to_string())]);
        }
        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_issue_worklog(
        &self,
        issue_id_or_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
        started_after: Option<i64>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageOfWorklogs, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/worklog",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        if let Some(ref s) = started_after {
            req_builder = req_builder.query(&[("startedAfter", &s.to_string())]);
        }
        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_worklog(
        &self,
        issue_id_or_key: &str,
        id: &str,
        expand: Option<&str>,
    ) -> Result<crate::models::Worklog, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/worklog/{id}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_worklogs_for_ids_post(
        &self,
        worklog_ids_request_bean: crate::models::WorklogIdsRequestBean,
        expand: Option<&str>,
    ) -> Result<Vec<crate::models::Worklog>, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/worklog/list", configuration.base_path);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&worklog_ids_request_bean);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn update_worklog_put(
        &self,
        issue_id_or_key: &str,
        id: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        notify_users: Option<bool>,
        adjust_estimate: Option<&str>,
        new_estimate: Option<&str>,
        expand: Option<&str>,
        override_editable_flag: Option<bool>,
    ) -> Result<crate::models::Worklog, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/worklog/{id}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref s) = notify_users {
            req_builder = req_builder.query(&[("notifyUsers", &s.to_string())]);
        }
        if let Some(ref s) = adjust_estimate {
            req_builder = req_builder.query(&[("adjustEstimate", &s.to_string())]);
        }
        if let Some(ref s) = new_estimate {
            req_builder = req_builder.query(&[("newEstimate", &s.to_string())]);
        }
        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref s) = override_editable_flag {
            req_builder = req_builder.query(&[("overrideEditableFlag", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
