/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct IssueSecurityLevelApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl IssueSecurityLevelApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> IssueSecurityLevelApiClient {
        IssueSecurityLevelApiClient { configuration }
    }
}

pub trait IssueSecurityLevelApi {
    fn get_issue_security_level(&self, id: &str) -> Result<crate::models::SecurityLevel, Error>;
}

impl IssueSecurityLevelApi for IssueSecurityLevelApiClient {
    fn get_issue_security_level(&self, id: &str) -> Result<crate::models::SecurityLevel, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/securitylevel/{id}",
            configuration.base_path,
            id = crate::apis::urlencode(id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
