/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct IssueWorklogPropertiesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl IssueWorklogPropertiesApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> IssueWorklogPropertiesApiClient {
        IssueWorklogPropertiesApiClient { configuration }
    }
}

pub trait IssueWorklogPropertiesApi {
    fn delete_worklog_property(
        &self,
        issue_id_or_key: &str,
        worklog_id: &str,
        property_key: &str,
    ) -> Result<(), Error>;
    fn get_worklog_property(
        &self,
        issue_id_or_key: &str,
        worklog_id: &str,
        property_key: &str,
    ) -> Result<crate::models::EntityProperty, Error>;
    fn get_worklog_property_keys(
        &self,
        issue_id_or_key: &str,
        worklog_id: &str,
    ) -> Result<crate::models::PropertyKeys, Error>;
    fn set_worklog_property_put(
        &self,
        issue_id_or_key: &str,
        worklog_id: &str,
        property_key: &str,
        body: serde_json::Value,
    ) -> Result<serde_json::Value, Error>;
}

impl IssueWorklogPropertiesApi for IssueWorklogPropertiesApiClient {
    fn delete_worklog_property(
        &self,
        issue_id_or_key: &str,
        worklog_id: &str,
        property_key: &str,
    ) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            worklogId = crate::apis::urlencode(worklog_id),
            propertyKey = crate::apis::urlencode(property_key)
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn get_worklog_property(
        &self,
        issue_id_or_key: &str,
        worklog_id: &str,
        property_key: &str,
    ) -> Result<crate::models::EntityProperty, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            worklogId = crate::apis::urlencode(worklog_id),
            propertyKey = crate::apis::urlencode(property_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_worklog_property_keys(
        &self,
        issue_id_or_key: &str,
        worklog_id: &str,
    ) -> Result<crate::models::PropertyKeys, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            worklogId = crate::apis::urlencode(worklog_id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn set_worklog_property_put(
        &self,
        issue_id_or_key: &str,
        worklog_id: &str,
        property_key: &str,
        body: serde_json::Value,
    ) -> Result<serde_json::Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/worklog/{worklogId}/properties/{propertyKey}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            worklogId = crate::apis::urlencode(worklog_id),
            propertyKey = crate::apis::urlencode(property_key)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
