/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct IssueCustomFieldOptionsAppsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl IssueCustomFieldOptionsAppsApiClient {
    pub fn new(
        configuration: Rc<configuration::Configuration>,
    ) -> IssueCustomFieldOptionsAppsApiClient {
        IssueCustomFieldOptionsAppsApiClient { configuration }
    }
}

pub trait IssueCustomFieldOptionsAppsApi {
    fn create_issue_field_option_post(
        &self,
        field_key: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
    ) -> Result<crate::models::IssueFieldOption, Error>;
    fn delete_issue_field_option(
        &self,
        field_key: &str,
        option_id: i64,
    ) -> Result<serde_json::Value, Error>;
    fn get_all_issue_field_options(
        &self,
        field_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
    ) -> Result<crate::models::PageBeanIssueFieldOption, Error>;
    fn get_issue_field_option(
        &self,
        field_key: &str,
        option_id: i64,
    ) -> Result<crate::models::IssueFieldOption, Error>;
    fn get_selectable_issue_field_options(
        &self,
        field_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
        project_id: Option<i64>,
    ) -> Result<crate::models::PageBeanIssueFieldOption, Error>;
    fn get_visible_issue_field_options(
        &self,
        field_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
        project_id: Option<i64>,
    ) -> Result<crate::models::PageBeanIssueFieldOption, Error>;
    fn replace_issue_field_option_delete(
        &self,
        field_key: &str,
        option_id: i64,
        replace_with: Option<i64>,
        jql: Option<&str>,
    ) -> Result<(), Error>;
    fn update_issue_field_option_put(
        &self,
        field_key: &str,
        option_id: i64,
        issue_field_option: crate::models::IssueFieldOption,
    ) -> Result<crate::models::IssueFieldOption, Error>;
}

impl IssueCustomFieldOptionsAppsApi for IssueCustomFieldOptionsAppsApiClient {
    fn create_issue_field_option_post(
        &self,
        field_key: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
    ) -> Result<crate::models::IssueFieldOption, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/field/{fieldKey}/option",
            configuration.base_path,
            fieldKey = crate::apis::urlencode(field_key)
        );
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn delete_issue_field_option(
        &self,
        field_key: &str,
        option_id: i64,
    ) -> Result<serde_json::Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/field/{fieldKey}/option/{optionId}",
            configuration.base_path,
            fieldKey = crate::apis::urlencode(field_key),
            optionId = option_id
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_all_issue_field_options(
        &self,
        field_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
    ) -> Result<crate::models::PageBeanIssueFieldOption, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/field/{fieldKey}/option",
            configuration.base_path,
            fieldKey = crate::apis::urlencode(field_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_issue_field_option(
        &self,
        field_key: &str,
        option_id: i64,
    ) -> Result<crate::models::IssueFieldOption, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/field/{fieldKey}/option/{optionId}",
            configuration.base_path,
            fieldKey = crate::apis::urlencode(field_key),
            optionId = option_id
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_selectable_issue_field_options(
        &self,
        field_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
        project_id: Option<i64>,
    ) -> Result<crate::models::PageBeanIssueFieldOption, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/field/{fieldKey}/option/suggestions/edit",
            configuration.base_path,
            fieldKey = crate::apis::urlencode(field_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        if let Some(ref s) = project_id {
            req_builder = req_builder.query(&[("projectId", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_visible_issue_field_options(
        &self,
        field_key: &str,
        start_at: Option<i64>,
        max_results: Option<i32>,
        project_id: Option<i64>,
    ) -> Result<crate::models::PageBeanIssueFieldOption, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/field/{fieldKey}/option/suggestions/search",
            configuration.base_path,
            fieldKey = crate::apis::urlencode(field_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        if let Some(ref s) = project_id {
            req_builder = req_builder.query(&[("projectId", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn replace_issue_field_option_delete(
        &self,
        field_key: &str,
        option_id: i64,
        replace_with: Option<i64>,
        jql: Option<&str>,
    ) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/field/{fieldKey}/option/{optionId}/issue",
            configuration.base_path,
            fieldKey = crate::apis::urlencode(field_key),
            optionId = option_id
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref s) = replace_with {
            req_builder = req_builder.query(&[("replaceWith", &s.to_string())]);
        }
        if let Some(ref s) = jql {
            req_builder = req_builder.query(&[("jql", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn update_issue_field_option_put(
        &self,
        field_key: &str,
        option_id: i64,
        issue_field_option: crate::models::IssueFieldOption,
    ) -> Result<crate::models::IssueFieldOption, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/field/{fieldKey}/option/{optionId}",
            configuration.base_path,
            fieldKey = crate::apis::urlencode(field_key),
            optionId = option_id
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&issue_field_option);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
