/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct IssueRemoteLinksApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl IssueRemoteLinksApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> IssueRemoteLinksApiClient {
        IssueRemoteLinksApiClient { configuration }
    }
}

pub trait IssueRemoteLinksApi {
    fn create_or_update_remote_issue_link_post(
        &self,
        issue_id_or_key: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
    ) -> Result<crate::models::RemoteIssueLinkIdentifies, Error>;
    fn delete_remote_issue_link_by_global_id(
        &self,
        issue_id_or_key: &str,
        global_id: &str,
    ) -> Result<(), Error>;
    fn delete_remote_issue_link_by_id(
        &self,
        issue_id_or_key: &str,
        link_id: &str,
    ) -> Result<(), Error>;
    fn get_remote_issue_link_by_id(
        &self,
        issue_id_or_key: &str,
        link_id: &str,
    ) -> Result<crate::models::RemoteIssueLink, Error>;
    fn get_remote_issue_links(
        &self,
        issue_id_or_key: &str,
        global_id: Option<&str>,
    ) -> Result<crate::models::RemoteIssueLink, Error>;
    fn update_remote_issue_link_put(
        &self,
        issue_id_or_key: &str,
        link_id: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
    ) -> Result<serde_json::Value, Error>;
}

impl IssueRemoteLinksApi for IssueRemoteLinksApiClient {
    fn create_or_update_remote_issue_link_post(
        &self,
        issue_id_or_key: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
    ) -> Result<crate::models::RemoteIssueLinkIdentifies, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/remotelink",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key)
        );
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn delete_remote_issue_link_by_global_id(
        &self,
        issue_id_or_key: &str,
        global_id: &str,
    ) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/remotelink",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key)
        );
        let mut req_builder = client.delete(uri_str.as_str());

        req_builder = req_builder.query(&[("globalId", &global_id.to_string())]);
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn delete_remote_issue_link_by_id(
        &self,
        issue_id_or_key: &str,
        link_id: &str,
    ) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/remotelink/{linkId}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            linkId = crate::apis::urlencode(link_id)
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn get_remote_issue_link_by_id(
        &self,
        issue_id_or_key: &str,
        link_id: &str,
    ) -> Result<crate::models::RemoteIssueLink, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/remotelink/{linkId}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            linkId = crate::apis::urlencode(link_id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_remote_issue_links(
        &self,
        issue_id_or_key: &str,
        global_id: Option<&str>,
    ) -> Result<crate::models::RemoteIssueLink, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/remotelink",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = global_id {
            req_builder = req_builder.query(&[("globalId", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn update_remote_issue_link_put(
        &self,
        issue_id_or_key: &str,
        link_id: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
    ) -> Result<serde_json::Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/issue/{issueIdOrKey}/remotelink/{linkId}",
            configuration.base_path,
            issueIdOrKey = crate::apis::urlencode(issue_id_or_key),
            linkId = crate::apis::urlencode(link_id)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
