/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct PermissionsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl PermissionsApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> PermissionsApiClient {
        PermissionsApiClient { configuration }
    }
}

pub trait PermissionsApi {
    fn get_all_permissions(&self) -> Result<crate::models::Permissions, Error>;
    fn get_bulk_permissions_post(
        &self,
        bulk_permissions_request_bean: crate::models::BulkPermissionsRequestBean,
    ) -> Result<crate::models::BulkPermissionGrants, Error>;
    fn get_my_permissions(
        &self,
        project_key: Option<&str>,
        project_id: Option<&str>,
        issue_key: Option<&str>,
        issue_id: Option<&str>,
        permissions: Option<&str>,
        project_uuid: Option<&str>,
        project_configuration_uuid: Option<&str>,
    ) -> Result<crate::models::Permissions, Error>;
    fn get_permitted_projects_post(
        &self,
        permissions_keys_bean: crate::models::PermissionsKeysBean,
    ) -> Result<crate::models::PermittedProjects, Error>;
}

impl PermissionsApi for PermissionsApiClient {
    fn get_all_permissions(&self) -> Result<crate::models::Permissions, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/permissions", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_bulk_permissions_post(
        &self,
        bulk_permissions_request_bean: crate::models::BulkPermissionsRequestBean,
    ) -> Result<crate::models::BulkPermissionGrants, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/permissions/check", configuration.base_path);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&bulk_permissions_request_bean);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_my_permissions(
        &self,
        project_key: Option<&str>,
        project_id: Option<&str>,
        issue_key: Option<&str>,
        issue_id: Option<&str>,
        permissions: Option<&str>,
        project_uuid: Option<&str>,
        project_configuration_uuid: Option<&str>,
    ) -> Result<crate::models::Permissions, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/mypermissions", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = project_key {
            req_builder = req_builder.query(&[("projectKey", &s.to_string())]);
        }
        if let Some(ref s) = project_id {
            req_builder = req_builder.query(&[("projectId", &s.to_string())]);
        }
        if let Some(ref s) = issue_key {
            req_builder = req_builder.query(&[("issueKey", &s.to_string())]);
        }
        if let Some(ref s) = issue_id {
            req_builder = req_builder.query(&[("issueId", &s.to_string())]);
        }
        if let Some(ref s) = permissions {
            req_builder = req_builder.query(&[("permissions", &s.to_string())]);
        }
        if let Some(ref s) = project_uuid {
            req_builder = req_builder.query(&[("projectUuid", &s.to_string())]);
        }
        if let Some(ref s) = project_configuration_uuid {
            req_builder = req_builder.query(&[("projectConfigurationUuid", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_permitted_projects_post(
        &self,
        permissions_keys_bean: crate::models::PermissionsKeysBean,
    ) -> Result<crate::models::PermittedProjects, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/permissions/project", configuration.base_path);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&permissions_keys_bean);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
