/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct ProjectPermissionSchemesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl ProjectPermissionSchemesApiClient {
    pub fn new(
        configuration: Rc<configuration::Configuration>,
    ) -> ProjectPermissionSchemesApiClient {
        ProjectPermissionSchemesApiClient { configuration }
    }
}

pub trait ProjectPermissionSchemesApi {
    fn assign_permission_scheme_put(
        &self,
        project_key_or_id: &str,
        id_bean: crate::models::IdBean,
        expand: Option<&str>,
    ) -> Result<crate::models::PermissionScheme, Error>;
    fn get_assigned_permission_scheme(
        &self,
        project_key_or_id: &str,
        expand: Option<&str>,
    ) -> Result<crate::models::PermissionScheme, Error>;
    fn get_issue_security_scheme(
        &self,
        project_key_or_id: &str,
    ) -> Result<crate::models::SecurityScheme, Error>;
    fn get_security_levels_for_project(
        &self,
        project_key_or_id: &str,
    ) -> Result<crate::models::ProjectIssueSecurityLevels, Error>;
}

impl ProjectPermissionSchemesApi for ProjectPermissionSchemesApiClient {
    fn assign_permission_scheme_put(
        &self,
        project_key_or_id: &str,
        id_bean: crate::models::IdBean,
        expand: Option<&str>,
    ) -> Result<crate::models::PermissionScheme, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/{projectKeyOrId}/permissionscheme",
            configuration.base_path,
            projectKeyOrId = crate::apis::urlencode(project_key_or_id)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&id_bean);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_assigned_permission_scheme(
        &self,
        project_key_or_id: &str,
        expand: Option<&str>,
    ) -> Result<crate::models::PermissionScheme, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/{projectKeyOrId}/permissionscheme",
            configuration.base_path,
            projectKeyOrId = crate::apis::urlencode(project_key_or_id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_issue_security_scheme(
        &self,
        project_key_or_id: &str,
    ) -> Result<crate::models::SecurityScheme, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/{projectKeyOrId}/issuesecuritylevelscheme",
            configuration.base_path,
            projectKeyOrId = crate::apis::urlencode(project_key_or_id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_security_levels_for_project(
        &self,
        project_key_or_id: &str,
    ) -> Result<crate::models::ProjectIssueSecurityLevels, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/{projectKeyOrId}/securitylevel",
            configuration.base_path,
            projectKeyOrId = crate::apis::urlencode(project_key_or_id)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
