/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct ProjectTypesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl ProjectTypesApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> ProjectTypesApiClient {
        ProjectTypesApiClient { configuration }
    }
}

pub trait ProjectTypesApi {
    fn get_accessible_project_type_by_key(
        &self,
        project_type_key: &str,
    ) -> Result<crate::models::ProjectType, Error>;
    fn get_all_project_types(&self) -> Result<Vec<crate::models::ProjectType>, Error>;
    fn get_project_type_by_key(
        &self,
        project_type_key: &str,
    ) -> Result<crate::models::ProjectType, Error>;
}

impl ProjectTypesApi for ProjectTypesApiClient {
    fn get_accessible_project_type_by_key(
        &self,
        project_type_key: &str,
    ) -> Result<crate::models::ProjectType, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/type/{projectTypeKey}/accessible",
            configuration.base_path,
            projectTypeKey = crate::apis::urlencode(project_type_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_all_project_types(&self) -> Result<Vec<crate::models::ProjectType>, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/project/type", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_project_type_by_key(
        &self,
        project_type_key: &str,
    ) -> Result<crate::models::ProjectType, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/type/{projectTypeKey}",
            configuration.base_path,
            projectTypeKey = crate::apis::urlencode(project_type_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
