/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct ProjectKeyAndNameValidationApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl ProjectKeyAndNameValidationApiClient {
    pub fn new(
        configuration: Rc<configuration::Configuration>,
    ) -> ProjectKeyAndNameValidationApiClient {
        ProjectKeyAndNameValidationApiClient { configuration }
    }
}

pub trait ProjectKeyAndNameValidationApi {
    fn get_valid_project_key(&self, key: Option<&str>) -> Result<String, Error>;
    fn get_valid_project_name(&self, name: &str) -> Result<String, Error>;
    fn validate_project_key_get(
        &self,
        key: Option<&str>,
    ) -> Result<crate::models::ErrorCollection, Error>;
}

impl ProjectKeyAndNameValidationApi for ProjectKeyAndNameValidationApiClient {
    fn get_valid_project_key(&self, key: Option<&str>) -> Result<String, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/projectvalidate/validProjectKey",
            configuration.base_path
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = key {
            req_builder = req_builder.query(&[("key", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_valid_project_name(&self, name: &str) -> Result<String, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/projectvalidate/validProjectName",
            configuration.base_path
        );
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("name", &name.to_string())]);
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn validate_project_key_get(
        &self,
        key: Option<&str>,
    ) -> Result<crate::models::ErrorCollection, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/projectvalidate/key", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = key {
            req_builder = req_builder.query(&[("key", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
