/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct ProjectAvatarsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl ProjectAvatarsApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> ProjectAvatarsApiClient {
        ProjectAvatarsApiClient { configuration }
    }
}

pub trait ProjectAvatarsApi {
    fn create_project_avatar_post(
        &self,
        project_id_or_key: &str,
        body: serde_json::Value,
        x: Option<i32>,
        y: Option<i32>,
        size: Option<i32>,
    ) -> Result<crate::models::Avatar, Error>;
    fn delete_project_avatar(&self, project_id_or_key: &str, id: i64) -> Result<(), Error>;
    fn get_all_project_avatars(
        &self,
        project_id_or_key: &str,
    ) -> Result<crate::models::ProjectAvatars, Error>;
    fn update_project_avatar_put(
        &self,
        project_id_or_key: &str,
        avatar: crate::models::Avatar,
    ) -> Result<serde_json::Value, Error>;
}

impl ProjectAvatarsApi for ProjectAvatarsApiClient {
    fn create_project_avatar_post(
        &self,
        project_id_or_key: &str,
        body: serde_json::Value,
        x: Option<i32>,
        y: Option<i32>,
        size: Option<i32>,
    ) -> Result<crate::models::Avatar, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/{projectIdOrKey}/avatar2",
            configuration.base_path,
            projectIdOrKey = crate::apis::urlencode(project_id_or_key)
        );
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref s) = x {
            req_builder = req_builder.query(&[("x", &s.to_string())]);
        }
        if let Some(ref s) = y {
            req_builder = req_builder.query(&[("y", &s.to_string())]);
        }
        if let Some(ref s) = size {
            req_builder = req_builder.query(&[("size", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn delete_project_avatar(&self, project_id_or_key: &str, id: i64) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/{projectIdOrKey}/avatar/{id}",
            configuration.base_path,
            projectIdOrKey = crate::apis::urlencode(project_id_or_key),
            id = id
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn get_all_project_avatars(
        &self,
        project_id_or_key: &str,
    ) -> Result<crate::models::ProjectAvatars, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/{projectIdOrKey}/avatars",
            configuration.base_path,
            projectIdOrKey = crate::apis::urlencode(project_id_or_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn update_project_avatar_put(
        &self,
        project_id_or_key: &str,
        avatar: crate::models::Avatar,
    ) -> Result<serde_json::Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/project/{projectIdOrKey}/avatar",
            configuration.base_path,
            projectIdOrKey = crate::apis::urlencode(project_id_or_key)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&avatar);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
