/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct UserPropertiesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl UserPropertiesApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> UserPropertiesApiClient {
        UserPropertiesApiClient { configuration }
    }
}

pub trait UserPropertiesApi {
    fn delete_user_property(
        &self,
        property_key: &str,
        account_id: Option<&str>,
        user_key: Option<&str>,
        username: Option<&str>,
    ) -> Result<(), Error>;
    fn get_user_property(
        &self,
        property_key: &str,
        account_id: Option<&str>,
        user_key: Option<&str>,
        username: Option<&str>,
    ) -> Result<crate::models::EntityProperty, Error>;
    fn get_user_property_keys(
        &self,
        account_id: Option<&str>,
        user_key: Option<&str>,
        username: Option<&str>,
    ) -> Result<crate::models::PropertyKeys, Error>;
    fn set_user_property_put(
        &self,
        property_key: &str,
        body: serde_json::Value,
        account_id: Option<&str>,
        user_key: Option<&str>,
        username: Option<&str>,
    ) -> Result<serde_json::Value, Error>;
}

impl UserPropertiesApi for UserPropertiesApiClient {
    fn delete_user_property(
        &self,
        property_key: &str,
        account_id: Option<&str>,
        user_key: Option<&str>,
        username: Option<&str>,
    ) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/user/properties/{propertyKey}",
            configuration.base_path,
            propertyKey = crate::apis::urlencode(property_key)
        );
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref s) = account_id {
            req_builder = req_builder.query(&[("accountId", &s.to_string())]);
        }
        if let Some(ref s) = user_key {
            req_builder = req_builder.query(&[("userKey", &s.to_string())]);
        }
        if let Some(ref s) = username {
            req_builder = req_builder.query(&[("username", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn get_user_property(
        &self,
        property_key: &str,
        account_id: Option<&str>,
        user_key: Option<&str>,
        username: Option<&str>,
    ) -> Result<crate::models::EntityProperty, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/user/properties/{propertyKey}",
            configuration.base_path,
            propertyKey = crate::apis::urlencode(property_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = account_id {
            req_builder = req_builder.query(&[("accountId", &s.to_string())]);
        }
        if let Some(ref s) = user_key {
            req_builder = req_builder.query(&[("userKey", &s.to_string())]);
        }
        if let Some(ref s) = username {
            req_builder = req_builder.query(&[("username", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_user_property_keys(
        &self,
        account_id: Option<&str>,
        user_key: Option<&str>,
        username: Option<&str>,
    ) -> Result<crate::models::PropertyKeys, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/user/properties", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = account_id {
            req_builder = req_builder.query(&[("accountId", &s.to_string())]);
        }
        if let Some(ref s) = user_key {
            req_builder = req_builder.query(&[("userKey", &s.to_string())]);
        }
        if let Some(ref s) = username {
            req_builder = req_builder.query(&[("username", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn set_user_property_put(
        &self,
        property_key: &str,
        body: serde_json::Value,
        account_id: Option<&str>,
        user_key: Option<&str>,
        username: Option<&str>,
    ) -> Result<serde_json::Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/user/properties/{propertyKey}",
            configuration.base_path,
            propertyKey = crate::apis::urlencode(property_key)
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref s) = account_id {
            req_builder = req_builder.query(&[("accountId", &s.to_string())]);
        }
        if let Some(ref s) = user_key {
            req_builder = req_builder.query(&[("userKey", &s.to_string())]);
        }
        if let Some(ref s) = username {
            req_builder = req_builder.query(&[("username", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
