/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct WorkflowsApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl WorkflowsApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> WorkflowsApiClient {
        WorkflowsApiClient { configuration }
    }
}

pub trait WorkflowsApi {
    fn get_all_workflows(
        &self,
        workflow_name: Option<&str>,
    ) -> Result<Vec<crate::models::DeprecatedWorkflow>, Error>;
    fn get_workflows_paginated(
        &self,
        start_at: Option<i64>,
        max_results: Option<i32>,
        workflow_name: Option<Vec<String>>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanWorkflow, Error>;
}

impl WorkflowsApi for WorkflowsApiClient {
    fn get_all_workflows(
        &self,
        workflow_name: Option<&str>,
    ) -> Result<Vec<crate::models::DeprecatedWorkflow>, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/workflow", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = workflow_name {
            req_builder = req_builder.query(&[("workflowName", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_workflows_paginated(
        &self,
        start_at: Option<i64>,
        max_results: Option<i32>,
        workflow_name: Option<Vec<String>>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanWorkflow, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/workflow/search", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        if let Some(ref s) = workflow_name {
            req_builder = req_builder.query(&[(
                "workflowName",
                &s.into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]);
        }
        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
