/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct WorkflowStatusCategoriesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl WorkflowStatusCategoriesApiClient {
    pub fn new(
        configuration: Rc<configuration::Configuration>,
    ) -> WorkflowStatusCategoriesApiClient {
        WorkflowStatusCategoriesApiClient { configuration }
    }
}

pub trait WorkflowStatusCategoriesApi {
    fn get_status_categories(&self) -> Result<Vec<crate::models::StatusCategory>, Error>;
    fn get_status_category(&self, id_or_key: &str) -> Result<crate::models::StatusCategory, Error>;
}

impl WorkflowStatusCategoriesApi for WorkflowStatusCategoriesApiClient {
    fn get_status_categories(&self) -> Result<Vec<crate::models::StatusCategory>, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/rest/api/3/statuscategory", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn get_status_category(&self, id_or_key: &str) -> Result<crate::models::StatusCategory, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/statuscategory/{idOrKey}",
            configuration.base_path,
            idOrKey = crate::apis::urlencode(id_or_key)
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
