/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct WorkflowTransitionRulesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl WorkflowTransitionRulesApiClient {
    pub fn new(
        configuration: Rc<configuration::Configuration>,
    ) -> WorkflowTransitionRulesApiClient {
        WorkflowTransitionRulesApiClient { configuration }
    }
}

pub trait WorkflowTransitionRulesApi {
    fn get_workflow_transition_rule_configurations(
        &self,
        types: Vec<String>,
        start_at: Option<i64>,
        max_results: Option<i32>,
        keys: Option<Vec<String>>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanWorkflowTransitionRules, Error>;
    fn update_workflow_transition_rule_configurations_put(
        &self,
        workflow_transition_rules_update: crate::models::WorkflowTransitionRulesUpdate,
    ) -> Result<crate::models::WorkflowTransitionRulesUpdateErrors, Error>;
}

impl WorkflowTransitionRulesApi for WorkflowTransitionRulesApiClient {
    fn get_workflow_transition_rule_configurations(
        &self,
        types: Vec<String>,
        start_at: Option<i64>,
        max_results: Option<i32>,
        keys: Option<Vec<String>>,
        expand: Option<&str>,
    ) -> Result<crate::models::PageBeanWorkflowTransitionRules, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/workflow/rule/config",
            configuration.base_path
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = start_at {
            req_builder = req_builder.query(&[("startAt", &s.to_string())]);
        }
        if let Some(ref s) = max_results {
            req_builder = req_builder.query(&[("maxResults", &s.to_string())]);
        }
        req_builder = req_builder.query(&[(
            "types",
            &types
                .into_iter()
                .map(|p| p.to_string())
                .collect::<Vec<String>>()
                .join(",")
                .to_string(),
        )]);
        if let Some(ref s) = keys {
            req_builder = req_builder.query(&[(
                "keys",
                &s.into_iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]);
        }
        if let Some(ref s) = expand {
            req_builder = req_builder.query(&[("expand", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn update_workflow_transition_rule_configurations_put(
        &self,
        workflow_transition_rules_update: crate::models::WorkflowTransitionRulesUpdate,
    ) -> Result<crate::models::WorkflowTransitionRulesUpdateErrors, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/workflow/rule/config",
            configuration.base_path
        );
        let mut req_builder = client.put(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&workflow_transition_rules_update);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
