/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::rc::Rc;

use reqwest;

use super::{configuration, Error};

pub struct WorkflowTransitionPropertiesApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl WorkflowTransitionPropertiesApiClient {
    pub fn new(
        configuration: Rc<configuration::Configuration>,
    ) -> WorkflowTransitionPropertiesApiClient {
        WorkflowTransitionPropertiesApiClient { configuration }
    }
}

pub trait WorkflowTransitionPropertiesApi {
    fn create_workflow_transition_property_post(
        &self,
        transition_id: i64,
        key: &str,
        workflow_name: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        workflow_mode: Option<&str>,
    ) -> Result<crate::models::WorkflowTransitionProperty, Error>;
    fn delete_workflow_transition_property(
        &self,
        transition_id: i64,
        key: &str,
        workflow_name: &str,
        workflow_mode: Option<&str>,
    ) -> Result<(), Error>;
    fn get_workflow_transition_properties(
        &self,
        transition_id: i64,
        workflow_name: &str,
        include_reserved_keys: Option<bool>,
        key: Option<&str>,
        workflow_mode: Option<&str>,
    ) -> Result<crate::models::WorkflowTransitionProperty, Error>;
    fn update_workflow_transition_property_put(
        &self,
        transition_id: i64,
        key: &str,
        workflow_name: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        workflow_mode: Option<&str>,
    ) -> Result<crate::models::WorkflowTransitionProperty, Error>;
}

impl WorkflowTransitionPropertiesApi for WorkflowTransitionPropertiesApiClient {
    fn create_workflow_transition_property_post(
        &self,
        transition_id: i64,
        key: &str,
        workflow_name: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        workflow_mode: Option<&str>,
    ) -> Result<crate::models::WorkflowTransitionProperty, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/workflow/transitions/{transitionId}/properties",
            configuration.base_path,
            transitionId = transition_id
        );
        let mut req_builder = client.post(uri_str.as_str());

        req_builder = req_builder.query(&[("key", &key.to_string())]);
        req_builder = req_builder.query(&[("workflowName", &workflow_name.to_string())]);
        if let Some(ref s) = workflow_mode {
            req_builder = req_builder.query(&[("workflowMode", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn delete_workflow_transition_property(
        &self,
        transition_id: i64,
        key: &str,
        workflow_name: &str,
        workflow_mode: Option<&str>,
    ) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/workflow/transitions/{transitionId}/properties",
            configuration.base_path,
            transitionId = transition_id
        );
        let mut req_builder = client.delete(uri_str.as_str());

        req_builder = req_builder.query(&[("key", &key.to_string())]);
        req_builder = req_builder.query(&[("workflowName", &workflow_name.to_string())]);
        if let Some(ref s) = workflow_mode {
            req_builder = req_builder.query(&[("workflowMode", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

    fn get_workflow_transition_properties(
        &self,
        transition_id: i64,
        workflow_name: &str,
        include_reserved_keys: Option<bool>,
        key: Option<&str>,
        workflow_mode: Option<&str>,
    ) -> Result<crate::models::WorkflowTransitionProperty, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/workflow/transitions/{transitionId}/properties",
            configuration.base_path,
            transitionId = transition_id
        );
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = include_reserved_keys {
            req_builder = req_builder.query(&[("includeReservedKeys", &s.to_string())]);
        }
        if let Some(ref s) = key {
            req_builder = req_builder.query(&[("key", &s.to_string())]);
        }
        req_builder = req_builder.query(&[("workflowName", &workflow_name.to_string())]);
        if let Some(ref s) = workflow_mode {
            req_builder = req_builder.query(&[("workflowMode", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

    fn update_workflow_transition_property_put(
        &self,
        transition_id: i64,
        key: &str,
        workflow_name: &str,
        request_body: ::std::collections::HashMap<String, serde_json::Value>,
        workflow_mode: Option<&str>,
    ) -> Result<crate::models::WorkflowTransitionProperty, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!(
            "{}/rest/api/3/workflow/transitions/{transitionId}/properties",
            configuration.base_path,
            transitionId = transition_id
        );
        let mut req_builder = client.put(uri_str.as_str());

        req_builder = req_builder.query(&[("key", &key.to_string())]);
        req_builder = req_builder.query(&[("workflowName", &workflow_name.to_string())]);
        if let Some(ref s) = workflow_mode {
            req_builder = req_builder.query(&[("workflowMode", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref auth_conf) = configuration.basic_auth {
            req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
        };
        req_builder = req_builder.json(&request_body);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }
}
