/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// FieldValueClause : A clause that asserts the current value of a field. For example, `summary ~ test`.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldValueClause {
    #[serde(rename = "field")]
    pub field: crate::models::JqlQueryField,
    /// The operator between the field and operand.
    #[serde(rename = "operator")]
    pub operator: String,
    #[serde(rename = "operand")]
    pub operand: crate::models::JqlQueryClauseOperand,
}

impl FieldValueClause {
    /// A clause that asserts the current value of a field. For example, `summary ~ test`.
    pub fn new(
        field: crate::models::JqlQueryField,
        operator: String,
        operand: crate::models::JqlQueryClauseOperand,
    ) -> FieldValueClause {
        FieldValueClause {
            field,
            operator,
            operand,
        }
    }
}
