/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// IssueLink : Details of a link between issues.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueLink {
    /// The ID of the issue link.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The URL of the issue link.
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub _self: Option<String>,
    /// The type of link between the issues.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<crate::models::IssueLinkType>,
    /// The issue the link joins to.
    #[serde(rename = "inwardIssue", skip_serializing_if = "Option::is_none")]
    pub inward_issue: Option<crate::models::LinkedIssue>,
    /// The issue the link originates from.
    #[serde(rename = "outwardIssue", skip_serializing_if = "Option::is_none")]
    pub outward_issue: Option<crate::models::LinkedIssue>,
}

impl IssueLink {
    /// Details of a link between issues.
    pub fn new() -> IssueLink {
        IssueLink {
            id: None,
            _self: None,
            _type: None,
            inward_issue: None,
            outward_issue: None,
        }
    }
}
