/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JiraExpressionsComplexityBean {
    /// The number of steps it took to evaluate the expression.
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<crate::models::JiraExpressionsComplexityValueBean>,
    /// The number of expensive operations executed while evaluating the expression. Expensive operations are those that load additional data, such as entity properties, comments, or custom fields.
    #[serde(
        rename = "expensiveOperations",
        skip_serializing_if = "Option::is_none"
    )]
    pub expensive_operations: Option<crate::models::JiraExpressionsComplexityValueBean>,
    /// The number of Jira REST API beans returned in the response.
    #[serde(rename = "beans", skip_serializing_if = "Option::is_none")]
    pub beans: Option<crate::models::JiraExpressionsComplexityValueBean>,
    /// The number of primitive values returned in the response.
    #[serde(rename = "primitiveValues", skip_serializing_if = "Option::is_none")]
    pub primitive_values: Option<crate::models::JiraExpressionsComplexityValueBean>,
}

impl JiraExpressionsComplexityBean {
    pub fn new() -> JiraExpressionsComplexityBean {
        JiraExpressionsComplexityBean {
            steps: None,
            expensive_operations: None,
            beans: None,
            primitive_values: None,
        }
    }
}
